### ISSUE TITLE
Is it possible to apply CSS style for the input box?

### ISSUE THREAD

**Issue by kishankarun** [riophae/vue-treeselect#137]
Hi @riophae ,

Thanks for the features provided already.
But it would be great if I had more control on the inputbox , so that I could apply some validation on the selected content and change its style for wrongly/not selected values

(Something like applying VeeValidate?)

![image](https://user-images.githubusercontent.com/323202/43570077-135c3ec0-9657-11e8-94d8-155e1b560a58.png)
(Wrong selected value - red border for input and red text)

**Comment by riophae** [comment]
Great suggestion! Actually this is a feature already in plan, just not implemented yet...

**Comment by kishankarun** [comment]
@riophae , Glad to know.
But do you have a quick solution for the same now :smile: ? Probably a workaround?

like you mentioned about text styling by

```
.vue-treeselect__menu {
  color: black;
}
```

**Comment by riophae** [comment]
Yeah, you can add your own CSS class and then apply new styles.

```vue
<template>
  <treeselect :class="treeselectClass" ... />
</template>

<script>
  export default {
    data() {
      fieldValid: false,
    },

    computed: {
      treeselectClass() {
        return {
          'treeselect-invalid': !this.fieldValid,
        }
      },
    },
  }
</script>
```

```css
/* Note that, you better don't change the border color when the menu is open. */
.vue-treeselect.field-invalid:not(.vue-treeselect--open) .vue-treeselect__control {
  border-color: red;
}

.vue-treeselect.field-invalid .vue-treeselect__single-value {
  color: red;
}
```
